INSERT INTO "relationship_type" ("relationship_type_id", "relationship_type") VALUES (1, 'Parent/guardian');

INSERT INTO "family_member" ("first_name", "middle_name", "last_name", "email", "phone_number")
VALUES
('Sheila', 'Wanda', 'Anthony', 'sheila.anthony278@outlook.com', '6289068217'),
('Corey', 'Kurt', 'Baldwin', 'corey.baldwin735@outlook.com', '232-878-2274'),
('Karen', 'Amy', 'Baldwin', 'karen.baldwin843@outlook.com', '6368141014'),
('Michelle', 'Emma', 'Bell', 'michelle.bell956@gmail.com', '(949)724-4559'),
('Mark', 'Anthony', 'Bradshaw', 'mark.bradshaw197@outlook.com', '372-233-4670'),
('Stephanie', 'Becky', 'Bradshaw', 'stephanie.bradshaw797@gmail.com', '271-982-6983'),
('Jesse', 'Timothy', 'Castro', 'jesse.castro376@gmail.com', '(630)429-9915'),
('Lisa', 'Melissa', 'Wilson', 'lisa.wilson932@icloud.com', '778-310-5644'),
('Kristina', 'Cindy', 'Cervantes', 'kristina.cervantes962@gmail.com', '2098727916'),
('Gabriel', 'Richard', 'Chambers', 'gabriel.chambers461@outlook.com', '(963)888-2492'),
('Vanessa', 'Samantha', 'Chambers', 'vanessa.chambers727@gmail.com', '(544)266-6877'),
('Jocelyn', 'Shannon', 'Chen', 'jocelyn.chen495@icloud.com', '870-554-9953'),
('Austin', 'Marc', 'Chung', 'austin.chung76@gmail.com', '9423786696'),
('Angelica', 'Marissa', 'Smith', 'angelica.smith840@icloud.com', '(608)810-4731'),
('Corey', 'Cameron', 'Daugherty', 'corey.daugherty150@outlook.com', '367-545-9355'),
('Jennifer', 'Sarah', 'Daugherty', 'jennifer.daugherty431@outlook.com', '(727)989-9144'),
('Stephanie', 'Sarah', 'Dunn', 'stephanie.dunn659@gmail.com', '6068484890'),
('Rebecca', 'Patricia', 'Figueroa', 'rebecca.figueroa358@outlook.com', '5927909243'),
('Todd', 'Chase', 'Finley', 'todd.finley183@outlook.com', '6872102412'),
('Ashlee', 'Tammy', 'Finley', 'ashlee.finley713@gmail.com', '(313)501-9265'),
('Karen', 'Katie', 'Frank', 'karen.frank266@icloud.com', '8616894999'),
('Angela', 'Nancy', 'Frost', 'angela.frost28@gmail.com', '652-991-3097'),
('Sean', 'Joseph', 'Gates', 'sean.gates3@outlook.com', '9889280097'),
('Wendy', 'Taylor', 'Odonnell', 'wendy.odonnell83@gmail.com', '349-328-2158'),
('Jenna', 'Rachel', 'Glenn', 'jenna.glenn159@outlook.com', '4252095417'),
('Timothy', 'Jason', 'Hanna', 'timothy.hanna792@gmail.com', '3153401874'),
('Tara', 'Heather', 'Hanna', 'tara.hanna467@icloud.com', '5852300571'),
('Donald', 'Angel', 'Hobbs', 'donald.hobbs850@gmail.com', '8523167768'),
('Susan', 'Tina', 'Allen', 'susan.allen243@outlook.com', '4418277332'),
('Kevin', 'Michael', 'Jones', 'kevin.jones617@gmail.com', '927-576-7528'),
('Victoria', 'Kristen', 'Jones', 'victoria.jones466@gmail.com', '(686)728-9377'),
('Tammy', 'Brooke', 'Lam', 'tammy.lam69@icloud.com', '299-924-4694'),
('Matthew', 'Juan', 'Lester', 'matthew.lester923@outlook.com', '9315182646'),
('Rebecca', 'Christina', 'Lester', 'rebecca.lester716@gmail.com', '7884528808'),
('Christopher', 'Christopher', 'Mack', 'christopher.mack954@outlook.com', '9876636029'),
('Anna', 'Melissa', 'Mack', 'anna.mack847@outlook.com', '(695)757-4248'),
('Michael', 'Jose', 'Mann', 'michael.mann857@outlook.com', '(406)402-2885'),
('Terri', 'Diane', 'Mann', 'terri.mann731@gmail.com', '307-323-9860'),
('Jimmy', 'Juan', 'Mayo', 'jimmy.mayo146@icloud.com', '(930)284-1493'),
('Denise', 'Jennifer', 'Mayo', 'denise.mayo71@icloud.com', '6623929188'),
('Brandon', 'Darin', 'Mcclain', 'brandon.mcclain386@gmail.com', '(304)553-4177'),
('Sara', 'Jessica', 'Mcclain', 'sara.mcclain740@gmail.com', '(429)824-0340'),
('Shannon', 'Kelly', 'Mendez', 'shannon.mendez808@outlook.com', '8609276181'),
('Scott', 'Casey', 'Monroe', 'scott.monroe781@icloud.com', '4059735782'),
('Morgan', 'Kelly', 'Cook', 'morgan.cook532@icloud.com', '787-788-5424'),
('James', 'Joseph', 'Moon', 'james.moon702@icloud.com', '799-302-7378'),
('Erica', 'Laurie', 'Moon', 'erica.moon647@icloud.com', '923-786-3401'),
('Daniel', 'Henry', 'Moyer', 'daniel.moyer964@gmail.com', '305-221-6601'),
('Ashley', 'Christina', 'Moyer', 'ashley.moyer237@gmail.com', '259-688-5723'),
('Regina', 'Andrea', 'Ochoa', 'regina.ochoa973@gmail.com', '3453820015'),
('Michelle', 'Nicole', 'Phelps', 'michelle.phelps5@gmail.com', '8686368466'),
('Randy', 'Chad', 'Pollard', 'randy.pollard170@outlook.com', '904-958-4286'),
('Katherine', 'Melissa', 'Pollard', 'katherine.pollard921@icloud.com', '2744798658'),
('Russell', 'Richard', 'Pope', 'russell.pope621@icloud.com', '6128664789'),
('Jennifer', 'Ashley', 'Reeves', 'jennifer.reeves680@gmail.com', '(238)659-0618'),
('Edward', 'Caleb', 'Prince', 'edward.prince33@icloud.com', '(934)530-3134'),
('Kim', 'Jessica', 'Prince', 'kim.prince991@gmail.com', '(536)551-0776'),
('Brian', 'Willie', 'Pugh', 'brian.pugh411@outlook.com', '(508)843-3243'),
('Ashley', 'Colleen', 'Torres', 'ashley.torres492@gmail.com', '8954718408'),
('Jesse', 'Craig', 'Schroeder', 'jesse.schroeder743@outlook.com', '494-435-6419'),
('Kathryn', 'Tonya', 'Schroeder', 'kathryn.schroeder662@gmail.com', '2965062974'),
('Erik', 'Nicholas', 'Soto', 'erik.soto423@outlook.com', '6705192871'),
('Angela', 'Angela', 'Soto', 'angela.soto875@icloud.com', '888-302-2778'),
('Robert', 'Dylan', 'Stout', 'robert.stout98@outlook.com', '250-798-0982'),
('Jessica', 'Deborah', 'Stout', 'jessica.stout925@icloud.com', '(592)225-3536'),
('Mark', 'Sean', 'Thomas', 'mark.thomas138@gmail.com', '2407592942'),
('Heather', 'Anne', 'Thomas', 'heather.thomas638@icloud.com', '624-938-0174');

INSERT INTO "family_group" ("student_id", "family_member_id", "parent_guardian", "emergency_pickup", "relationship_type_id")
VALUES
((SELECT student_id FROM student WHERE email = 'moanthony28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'sheila.anthony278@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'labaldwin28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'corey.baldwin735@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'labaldwin28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'karen.baldwin843@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'habell28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'michelle.bell956@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'ribradshaw28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'mark.bradshaw197@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'ribradshaw28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'stephanie.bradshaw797@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alcastro28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jesse.castro376@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alcastro28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'lisa.wilson932@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hacervantes28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'kristina.cervantes962@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lechambers28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'gabriel.chambers461@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lechambers28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'vanessa.chambers727@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'aschen28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jocelyn.chen495@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rochung28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'austin.chung76@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rochung28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'angelica.smith840@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'badaugherty28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'corey.daugherty150@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'badaugherty28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jennifer.daugherty431@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'iodunn28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'stephanie.dunn659@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alfigueroa28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'rebecca.figueroa358@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alfinley28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'todd.finley183@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alfinley28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'ashlee.finley713@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'jofrank28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'karen.frank266@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hefrost28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'angela.frost28@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'brgates28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'sean.gates3@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'brgates28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'wendy.odonnell83@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'frglenn28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jenna.glenn159@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rohanna28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'timothy.hanna792@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rohanna28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'tara.hanna467@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'inhobbs28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'donald.hobbs850@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'inhobbs28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'susan.allen243@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rijones28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'kevin.jones617@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rijones28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'victoria.jones466@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'halam28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'tammy.lam69@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'salester28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'matthew.lester923@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'salester28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'rebecca.lester716@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'damack28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'christopher.mack954@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'damack28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'anna.mack847@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'jomann28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'michael.mann857@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'jomann28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'terri.mann731@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'kemayo28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jimmy.mayo146@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'kemayo28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'denise.mayo71@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'tamcclain28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'brandon.mcclain386@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'tamcclain28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'sara.mcclain740@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'namendez28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'shannon.mendez808@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lumonroe28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'scott.monroe781@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lumonroe28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'morgan.cook532@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lamoon28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'james.moon702@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lamoon28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'erica.moon647@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'temoyer28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'daniel.moyer964@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'temoyer28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'ashley.moyer237@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'niochoa28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'regina.ochoa973@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'miphelps28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'michelle.phelps5@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rupollard28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'randy.pollard170@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rupollard28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'katherine.pollard921@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'dapope28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'russell.pope621@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'dapope28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jennifer.reeves680@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'leprince28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'edward.prince33@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'leprince28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'kim.prince991@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alpugh28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'brian.pugh411@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alpugh28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'ashley.torres492@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'evschroeder28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jesse.schroeder743@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'evschroeder28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'kathryn.schroeder662@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'umsoto28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'erik.soto423@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'umsoto28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'angela.soto875@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hestout28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'robert.stout98@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hestout28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jessica.stout925@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'tathomas28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'mark.thomas138@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'tathomas28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'heather.thomas638@icloud.com'), TRUE, TRUE, 1);

