version: '3.8'

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./schooldb/database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network
    restart: unless-stopped

  java:
    build: ./schooldb
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "35729:35729" # LiveReload server
    volumes:
      - ./schooldb:/app
    env_file:
      - .env
    networks:
      - network
    restart: unless-stopped

  titanweb:
    build:
      context: ./titanweb
      dockerfile: Dockerfile
    volumes:
      - ./titanweb:/srv/app
      - node_modules:/srv/app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    init: true
    stop_grace_period: 1s
    networks:
      - network

  chatlogic:
    build:
      context: ./chatlogic
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - GRAPHQL_URL=http://java:8080/graphql
    ports:
      - "8000:8000"
    volumes:
      - ./chatlogic/:/app
    networks:
      - network

volumes:
  postgres-data:
  node_modules:

networks:
  network:
    driver: bridge
