version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./schooldb/database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data #DB data persisting
    networks:
      - network

  java-springboot:
    build: ./java
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "35729:35729" # LiveReload server
    volumes:
      - ./java:/app
    environment:
      - SPRING_BOOT_DEVTOOLS_RESTART_ENABLED=true
      - DB_HOST=db # Can run Java server in IntelliJ instead of Docker
      - DB_PORT=5432 # Can run Java server in IntelliJ instead of Docker
    networks:
      - network

volumes:
  postgres-data:

networks:
  network:
    driver: bridge
