INSERT INTO "relationship_type" ("relationship_type_id", "relationship_type") VALUES (1, 'Parent/guardian');

INSERT INTO "family_member" ("first_name", "middle_name", "last_name", "email", "phone_number")
VALUES
('John', 'William', 'Anthony', 'john.anthony479@icloud.com', '6889554586'),
('Beth', 'Gabriella', 'Anthony', 'beth.anthony348@icloud.com', '2516762526'),
('David', 'Jason', 'Baldwin', 'david.baldwin162@icloud.com', '9283612858'),
('Karen', 'Courtney', 'Baldwin', 'karen.baldwin32@gmail.com', '5869705347'),
('Jason', 'James', 'Bell', 'jason.bell680@gmail.com', '4397512022'),
('Dawn', 'Michelle', 'Bell', 'dawn.bell298@gmail.com', '5788533926'),
('Peter', 'Matthew', 'Bradshaw', 'peter.bradshaw618@icloud.com', '4255843802'),
('Nicole', 'Kelly', 'Greene', 'nicole.greene980@outlook.com', '8716474176'),
('Craig', 'Matthew', 'Castro', 'craig.castro201@gmail.com', '8125084888'),
('Felicia', 'Holly', 'Castro', 'felicia.castro100@outlook.com', '2147410196'),
('Jeffrey', 'Noah', 'Cervantes', 'jeffrey.cervantes568@icloud.com', '8792167754'),
('Bridget', 'Crystal', 'Cervantes', 'bridget.cervantes347@icloud.com', '4524235998'),
('Caleb', 'Gabriel', 'Chambers', 'caleb.chambers701@outlook.com', '6539585678'),
('Teresa', 'Rebecca', 'Chambers', 'teresa.chambers79@outlook.com', '6578313992'),
('Larry', 'Steven', 'Chen', 'larry.chen389@icloud.com', '6399987656'),
('Melissa', 'Christine', 'Chen', 'melissa.chen146@icloud.com', '4419036216'),
('James', 'Ralph', 'Chung', 'james.chung552@gmail.com', '3289578767'),
('Amanda', 'Andrea', 'Chung', 'amanda.chung973@gmail.com', '3522896349'),
('Christopher', 'Benjamin', 'Daugherty', 'christopher.daugherty346@outlook.com', '8074553011'),
('Shelley', 'Barbara', 'Daugherty', 'shelley.daugherty997@icloud.com', '5267326174'),
('Thomas', 'Geoffrey', 'Dunn', 'thomas.dunn102@icloud.com', '2986463809'),
('Theresa', 'Lauren', 'Dunn', 'theresa.dunn178@outlook.com', '4253698786'),
('Stephanie', 'Angela', 'Figueroa', 'stephanie.figueroa68@gmail.com', '8928125133'),
('Richard', 'William', 'Finley', 'richard.finley806@outlook.com', '5696258192'),
('Jennifer', 'Barbara', 'Finley', 'jennifer.finley969@gmail.com', '7989388517'),
('James', 'Derek', 'Frank', 'james.frank402@gmail.com', '4164173879'),
('Haley', 'Brittany', 'Frank', 'haley.frank311@outlook.com', '3449822162'),
('Antonio', 'Christopher', 'Frost', 'antonio.frost518@icloud.com', '6757246577'),
('Jennifer', 'Maria', 'Frost', 'jennifer.frost848@icloud.com', '7398310024'),
('John', 'David', 'Gates', 'john.gates397@icloud.com', '5735715395'),
('Amber', 'Laura', 'Phillips', 'amber.phillips67@gmail.com', '2039814930'),
('Holly', 'Erika', 'Glenn', 'holly.glenn721@outlook.com', '8214992433'),
('Edward', 'Thomas', 'Hanna', 'edward.hanna766@gmail.com', '9858542137'),
('Briana', 'Crystal', 'Velasquez', 'briana.velasquez618@outlook.com', '6948090903'),
('Rodney', 'William', 'Hobbs', 'rodney.hobbs654@icloud.com', '3573114431'),
('Erin', 'Jamie', 'Hobbs', 'erin.hobbs644@icloud.com', '4358455061'),
('Justin', 'Jason', 'Jones', 'justin.jones297@gmail.com', '6899005757'),
('Shelby', 'Tanya', 'Jones', 'shelby.jones925@icloud.com', '3639541843'),
('Anthony', 'Matthew', 'Lam', 'anthony.lam729@gmail.com', '3545080798'),
('Caitlin', 'Cynthia', 'Lam', 'caitlin.lam12@outlook.com', '8619491201'),
('Russell', 'Marcus', 'Lester', 'russell.lester544@gmail.com', '5926820430'),
('Barbara', 'Amber', 'Miller', 'barbara.miller230@icloud.com', '9624449637'),
('Beth', 'Mary', 'Mack', 'beth.mack270@gmail.com', '2385716023'),
('Thomas', 'Jordan', 'Mann', 'thomas.mann308@icloud.com', '9513871969'),
('Kendra', 'Jessica', 'Mann', 'kendra.mann608@outlook.com', '8213485831'),
('Michael', 'Evan', 'Mayo', 'michael.mayo966@icloud.com', '7642473849'),
('Susan', 'Stacey', 'Mayo', 'susan.mayo919@icloud.com', '7808745569'),
('Gary', 'Ryan', 'Mcclain', 'gary.mcclain256@gmail.com', '9054222449'),
('Donna', 'Glenda', 'Mcclain', 'donna.mcclain341@outlook.com', '5967470363'),
('Randy', 'Austin', 'Mendez', 'randy.mendez833@gmail.com', '7003054521'),
('Ashley', 'Renee', 'Mendez', 'ashley.mendez528@gmail.com', '9754368143'),
('Edward', 'Austin', 'Monroe', 'edward.monroe559@gmail.com', '5659120978'),
('Judy', 'Debra', 'Monroe', 'judy.monroe924@outlook.com', '8638700989'),
('Brian', 'William', 'Moon', 'brian.moon314@icloud.com', '7979572896'),
('Melissa', 'Carol', 'Cooper', 'melissa.cooper5@icloud.com', '4805847748'),
('Andre', 'Troy', 'Moyer', 'andre.moyer219@gmail.com', '9587366831'),
('Christy', 'Marissa', 'Moyer', 'christy.moyer89@outlook.com', '3542493942'),
('Amy', 'Carrie', 'Ochoa', 'amy.ochoa918@outlook.com', '3548062883'),
('Aaron', 'Trevor', 'Phelps', 'aaron.phelps843@gmail.com', '8666878375'),
('Karen', 'Allison', 'Phelps', 'karen.phelps712@icloud.com', '4566416042'),
('Tammy', 'Monica', 'Pollard', 'tammy.pollard693@icloud.com', '4922528602'),
('Michael', 'Walter', 'Pope', 'michael.pope912@outlook.com', '6582434744'),
('Christina', 'Theresa', 'Pope', 'christina.pope62@outlook.com', '2443377658'),
('Cynthia', 'Patricia', 'Prince', 'cynthia.prince597@icloud.com', '9835347863'),
('Adam', 'Andrew', 'Pugh', 'adam.pugh539@gmail.com', '7975981900'),
('Debbie', 'Melissa', 'Pugh', 'debbie.pugh11@outlook.com', '2475284221'),
('Diane', 'Taylor', 'Schroeder', 'diane.schroeder488@outlook.com', '4656403283'),
('Andrew', 'Daniel', 'Soto', 'andrew.soto80@gmail.com', '7512748615'),
('Katherine', 'Stacey', 'Soto', 'katherine.soto134@outlook.com', '4083516122'),
('Joseph', 'Charles', 'Stout', 'joseph.stout18@outlook.com', '4194590740'),
('Cheryl', 'Lauren', 'Stout', 'cheryl.stout715@icloud.com', '9485948551'),
('Joseph', 'Gabriel', 'Thomas', 'joseph.thomas264@outlook.com', '7637398349'),
('Courtney', 'Leah', 'Young', 'courtney.young290@outlook.com', '4387307149');

INSERT INTO "family_group" ("student_id", "family_member_id", "parent_guardian", "emergency_pickup", "relationship_type_id")
VALUES
((SELECT student_id FROM student WHERE email = 'moanthony28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'john.anthony479@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'moanthony28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'beth.anthony348@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'labaldwin28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'david.baldwin162@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'labaldwin28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'karen.baldwin32@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'habell28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jason.bell680@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'habell28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'dawn.bell298@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'ribradshaw28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'peter.bradshaw618@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'ribradshaw28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'nicole.greene980@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alcastro28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'craig.castro201@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alcastro28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'felicia.castro100@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hacervantes28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jeffrey.cervantes568@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hacervantes28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'bridget.cervantes347@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lechambers28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'caleb.chambers701@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lechambers28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'teresa.chambers79@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'aschen28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'larry.chen389@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'aschen28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'melissa.chen146@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rochung28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'james.chung552@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rochung28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'amanda.chung973@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'badaugherty28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'christopher.daugherty346@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'badaugherty28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'shelley.daugherty997@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'iodunn28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'thomas.dunn102@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'iodunn28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'theresa.dunn178@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alfigueroa28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'stephanie.figueroa68@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alfinley28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'richard.finley806@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alfinley28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jennifer.finley969@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'jofrank28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'james.frank402@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'jofrank28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'haley.frank311@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hefrost28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'antonio.frost518@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hefrost28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'jennifer.frost848@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'brgates28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'john.gates397@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'brgates28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'amber.phillips67@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'frglenn28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'holly.glenn721@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rohanna28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'edward.hanna766@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rohanna28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'briana.velasquez618@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'inhobbs28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'rodney.hobbs654@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'inhobbs28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'erin.hobbs644@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rijones28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'justin.jones297@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rijones28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'shelby.jones925@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'halam28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'anthony.lam729@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'halam28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'caitlin.lam12@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'salester28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'russell.lester544@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'salester28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'barbara.miller230@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'damack28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'beth.mack270@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'jomann28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'thomas.mann308@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'jomann28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'kendra.mann608@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'kemayo28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'michael.mayo966@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'kemayo28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'susan.mayo919@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'tamcclain28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'gary.mcclain256@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'tamcclain28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'donna.mcclain341@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'namendez28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'randy.mendez833@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'namendez28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'ashley.mendez528@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lumonroe28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'edward.monroe559@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lumonroe28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'judy.monroe924@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lamoon28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'brian.moon314@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'lamoon28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'melissa.cooper5@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'temoyer28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'andre.moyer219@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'temoyer28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'christy.moyer89@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'niochoa28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'amy.ochoa918@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'miphelps28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'aaron.phelps843@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'miphelps28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'karen.phelps712@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'rupollard28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'tammy.pollard693@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'dapope28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'michael.pope912@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'dapope28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'christina.pope62@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'leprince28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'cynthia.prince597@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alpugh28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'adam.pugh539@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'alpugh28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'debbie.pugh11@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'evschroeder28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'diane.schroeder488@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'umsoto28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'andrew.soto80@gmail.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'umsoto28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'katherine.soto134@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hestout28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'joseph.stout18@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'hestout28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'cheryl.stout715@icloud.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'tathomas28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'joseph.thomas264@outlook.com'), TRUE, TRUE, 1),
((SELECT student_id FROM student WHERE email = 'tathomas28@titanacademy.edu'), (SELECT family_member_id FROM family_member WHERE email = 'courtney.young290@outlook.com'), TRUE, TRUE, 1);

